name: "census_utils"
version: "0.1.0"
config-version: 2
require-dbt-version: [">=1.0.0", "<2.0.0"]
models:
  census_utils:
    +schema: census

# This setting configures which "profile" dbt uses for this project.
profile: 'census_utils'

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

seeds:
  +schema: seeds

vars:
  internal_domain: ("'getcensus.com'", "'getcensus.co.uk'")
  internal_email_relation: 'census_internal_users'
  internal_email_column: 'email_address'
  internal_ip_relation: 'census_internal_users'
  internal_ip_column: 'ip_address'