version: 2
	sources:
	 - name: penta_raw
	 schema: "{{ var('penta_raw_schema', 'Penta') }}"
	 database: "{{ var('penta_raw_database', target.database) }}"
	 tables:
	 - name: changelog
	 description: |
	 	This table contains a row for every operation performed by Penta
	 	It includes the result of the operation, as well as any error messages.
	 columns:
	 - name: id
	 description: The id of the change
	 - name: event
	 description: The event that caused the change
	 - name: meta
	 description: Additional metadata about the change
	 - name: op_type
	 description: |
	 Whether the row was added, changed, or removed relative to the last run.