name: 'census_utils_integration_tests'
version: '1.0'
config-version: 2

profile: 'integration_tests'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
    - "target"
    - "dbt_packages"

seeds:
  census_utils_integration_tests:
    schema: seeds
    quote_columns: false
    ga4_client_id_results:
      +column_types:
        ga4_client_id: string
        unique_id: string
        timestamp: string
        client_id: string

vars: