version: 2

models:
  - name: test_clean_name
    tests:
      - dbt_utils.equality:
          compare_model: ref('cleaned_names')

  - name: test_is_personal_email
    tests:
      - dbt_utils.equality:
          compare_model: ref('personal_email_results')