version: 2

models:
  - name: test_clean_name
    tests:
      - dbt_utils.equality:
          compare_model: ref('cleaned_names')

  - name: test_is_personal_email
    tests:
      - dbt_utils.equality:
          compare_model: ref('personal_email_results')

  - name: test_extract_email_domain
    tests:
      - dbt_utils.equality:
          compare_model: ref('extract_email_domain_results')

  - name: test_country_name_to_country_code
    tests:
      - dbt_utils.equality:
          compare_model: ref('country_names_mapped')